
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SnApiService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://snapi.dataline.co.uk/SnAPIService.svc?wsdl")
public class SnApiService
    extends Service
{

    private final static URL SNAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException SNAPISERVICE_EXCEPTION;
    private final static QName SNAPISERVICE_QNAME = new QName("http://tempuri.org/", "SnApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://snapi.dataline.co.uk/SnAPIService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SNAPISERVICE_WSDL_LOCATION = url;
        SNAPISERVICE_EXCEPTION = e;
    }

    public SnApiService() {
        super(__getWsdlLocation(), SNAPISERVICE_QNAME);
    }

    public SnApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SNAPISERVICE_QNAME, features);
    }

    public SnApiService(URL wsdlLocation) {
        super(wsdlLocation, SNAPISERVICE_QNAME);
    }

    public SnApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SNAPISERVICE_QNAME, features);
    }

    public SnApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SnApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISnApiService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISnApiService")
    public ISnApiService getBasicHttpBindingISnApiService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISnApiService"), ISnApiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISnApiService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISnApiService")
    public ISnApiService getBasicHttpBindingISnApiService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISnApiService"), ISnApiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SNAPISERVICE_EXCEPTION!= null) {
            throw SNAPISERVICE_EXCEPTION;
        }
        return SNAPISERVICE_WSDL_LOCATION;
    }

}
